{% set name = "pytorch-dp" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/opacus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c37b91758028fabcf263d0385044c4a702e8d17198285106bccef5c10264c332

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - torchvision
    - pytorch
    - scipy
    - numpy

test:
  imports:
    - opacus

about:
  home: https://github.com/facebookresearch/pytorch-dp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pytorch-dp is a library that enables training PyTorch models with differential privacy.
  description: |
    pytorch-dp is a library that enables training PyTorch models with differential privacy. It
    supports training with minimal code changes required on the client, has little impact on training
    performance and allows the client to online track the privacy budget expended at any given moment.
  doc_url: https://pypi.org/project/pytorch-dp/#description
  dev_url: https://github.com/facebookresearch/pytorch-dp

extra:
  recipe-maintainers:
    - mxr-conda
    - JennaLipscomb
    - oblute
